Repository PlasticSCM/vscode-plasticscm, pull requests merged in 2020-01, with the labels that each got.

#37 Update package.json
  package.json
Labels: chore

#23 Automatic CI/CD
  azure-pipelines.yml
  package.json
Labels: In progress, devops

#38 Fix azure pipelines
  azure-pipelines.yml
  src/commands/index.ts
Labels: devops, testing
